name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release changes
        runs-on: ubuntu-22.04
        permissions:
            packages: write
            contents: write
            pull-requests: write

        steps:
            - name: Run Auto release
              run: |
                  npx auto init
                  npx auto create-labels
                  npx auto shipit
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
